from _typeshed import Incomplete
from dspy.predict.parameter import Parameter as Parameter
from dspy.primitives.prediction import Prediction as Prediction
from dspy.utils.callback import with_callbacks as with_callbacks

def single_query_passage(passages): ...

class Retrieve(Parameter):
    name: str
    input_variable: str
    desc: str
    stage: Incomplete
    k: Incomplete
    callbacks: Incomplete
    def __init__(self, k: int = 3, callbacks=None) -> None: ...
    def reset(self) -> None: ...
    def dump_state(self): ...
    def load_state(self, state) -> None: ...
    @with_callbacks
    def __call__(self, *args, **kwargs): ...
    def forward(self, query: str, k: int | None = None, **kwargs) -> list[str] | Prediction | list[Prediction]: ...
