import dspy
import weaviate
from dspy.dsp.utils import dotdict as dotdict
from dspy.primitives.prediction import Prediction as Prediction

class WeaviateRM(dspy.Retrieve):
    def __init__(self, weaviate_collection_name: str, weaviate_client: weaviate.WeaviateClient | weaviate.Client, weaviate_collection_text_key: str | None = "content", k: int = 3, tenant_id: str | None = None) -> None: ...
    def forward(self, query_or_queries: str | list[str], k: int | None = None, **kwargs) -> Prediction: ...
    def get_objects(self, num_samples: int, fields: list[str]) -> list[dict]: ...
    def insert(self, new_object_properties: dict): ...
