from dspy.dsp.utils.utils import print_message as print_message

def EM(prediction, answers_list): ...
def F1(prediction, answers_list): ...
def HotPotF1(prediction, answers_list): ...
def normalize_text(s): ...
def em_score(prediction, ground_truth): ...
def f1_score(prediction, ground_truth): ...
def hotpot_f1_score(prediction, ground_truth): ...
def precision_score(prediction, ground_truth): ...
def answer_exact_match(example, pred, trace=None, frac: float = 1.0): ...
def answer_passage_match(example, pred, trace=None): ...
