import abc
from abc import ABC, abstractmethod

class Proposer(ABC, metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    @abstractmethod
    def propose_instructions_for_program(self): ...
    def propose_instruction_for_predictor(self) -> None: ...
