from dspy.predict.parameter import Parameter as Parameter
from dspy.teleprompt.utils import get_signature as get_signature
from dspy.teleprompt.utils import new_getfile as new_getfile

def strip_prefix(text): ...
def create_instruction_set_history_string(base_program, trial_logs, top_n): ...
def parse_list_of_instructions(instruction_string): ...
def get_program_instruction_set_string(program): ...
def create_predictor_level_history_string(base_program, predictor_i, trial_logs, top_n): ...
def create_example_string(fields, example): ...
def get_dspy_source_code(module): ...
