from collections.abc import Awaitable, Callable
from typing import Any

from dspy.primitives.module import Module as Module

def get_async_max_workers(): ...
def get_limiter(): ...
def asyncify(program: Module) -> Callable[[Any, Any], Awaitable[Any]]: ...
