from typing import Any

from _typeshed import Incomplete

class Hasher:
    dispatch: dict
    m: Incomplete
    def __init__(self) -> None: ...
    @classmethod
    def hash_bytes(cls, value: bytes | list[bytes]) -> str: ...
    @classmethod
    def hash(cls, value: Any) -> str: ...
    def update(self, value: Any) -> None: ...
    def hexdigest(self) -> str: ...
