from _typeshed import Incomplete

LOGGING_LINE_FORMAT: str
LOGGING_DATETIME_FORMAT: str

class DSPyLoggingStream:
    def __init__(self) -> None: ...
    def write(self, text) -> None: ...
    def flush(self) -> None: ...
    @property
    def enabled(self): ...
    @enabled.setter
    def enabled(self, value) -> None: ...

DSPY_LOGGING_STREAM: Incomplete

def disable_logging() -> None: ...
def enable_logging() -> None: ...
def configure_dspy_loggers(root_module_name) -> None: ...
