from .copro_optimizer import COPRO as COPRO

class SignatureOptimizer(COPRO):
    def __init__(self, prompt_model=None, metric=None, breadth: int = 10, depth: int = 3, init_temperature: float = 1.4, verbose: bool = False, track_stats: bool = False) -> None: ...
    def compile(self, student, *, devset, eval_kwargs): ...
