from collections.abc import Generator

from _typeshed import Incomplete
from dspy.utils.saving import get_dependency_versions as get_dependency_versions

logger: Incomplete

class BaseModule:
    def __init__(self) -> None: ...
    def named_parameters(self): ...
    def named_sub_modules(self, type_=None, skip_compiled: bool = False) -> Generator[tuple[str, BaseModule]]: ...
    def parameters(self): ...
    def deepcopy(self): ...
    def reset_copy(self): ...
    def dump_state(self): ...
    def load_state(self, state) -> None: ...
    def save(self, path, save_program: bool = False, modules_to_serialize=None) -> None: ...
    def load(self, path) -> None: ...
