from typing import Any

class Example:
    def __init__(self, base=None, **kwargs) -> None: ...
    def __getattr__(self, key: str) -> Any: ...
    def __setattr__(self, key: str, value: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, key) -> bool: ...
    def __len__(self) -> int: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def keys(self, include_dspy: bool = False): ...
    def values(self, include_dspy: bool = False): ...
    def items(self, include_dspy: bool = False): ...
    def get(self, key, default=None): ...
    def with_inputs(self, *keys): ...
    def inputs(self): ...
    def labels(self): ...
    def __iter__(self): ...
    def copy(self, **kwargs): ...
    def without(self, *keys): ...
    def toDict(self): ...
