from collections.abc import Generator
from contextlib import contextmanager

from _typeshed import Incomplete
from dspy.dsp.utils.utils import dotdict as dotdict

DEFAULT_CONFIG: Incomplete
main_thread_config: Incomplete
config_owner_thread_id: Incomplete
config_owner_async_task: Incomplete
global_lock: Incomplete
thread_local_overrides: Incomplete

class Settings:
    def __new__(cls): ...
    @property
    def lock(self): ...
    def __getattr__(self, name): ...
    def __setattr__(self, name, value) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __contains__(self, key) -> bool: ...
    def get(self, key, default=None): ...
    def copy(self): ...
    @property
    def config(self): ...
    def configure(self, **kwargs) -> None: ...
    @contextmanager
    def context(self, **kwargs) -> Generator[None]: ...

settings: Incomplete
