from typing import Any

from dspy.adapters.json_adapter import JSONAdapter as JSONAdapter
from dspy.signatures.signature import Signature as Signature

COMMENT_SYMBOL: str

class BAMLAdapter(JSONAdapter):
    def format_field_description(self, signature: type[Signature]) -> str: ...
    def format_field_structure(self, signature: type[Signature]) -> str: ...
    def format_task_description(self, signature: type[Signature]) -> str: ...
    def format_user_message_content(self, signature: type[Signature], inputs: dict[str, Any], prefix: str = "", suffix: str = "", main_request: bool = False) -> str: ...
