from typing import Any

from dspy.adapters.types.base_type import Type as Type
from dspy.signatures.utils import get_dspy_field_type as get_dspy_field_type
from pydantic.fields import FieldInfo as FieldInfo

def serialize_for_json(value: Any) -> Any: ...
def format_field_value(field_info: FieldInfo, value: Any, assume_text: bool = True) -> str | dict: ...
def translate_field_type(field_name, field_info): ...
def find_enum_member(enum, identifier): ...
def parse_value(value, annotation): ...
def get_annotation_name(annotation): ...
def get_field_description_string(fields: dict) -> str: ...
