name: PR Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read
  contents: read

jobs:
  pr-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR title format
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
        requireScope: false
        validateSingleCommit: false

  check-changes:
    name: Check File Changes
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for large files
      run: |
        # Fail if any file is larger than 1MB
        find . -type f -size +1M | grep -v "^./.git" && exit 1 || exit 0
        
    - name: Check for sensitive files
      run: |
        # Check for common sensitive file patterns
        if find . -name "*.env" -o -name "*.key" -o -name "*.pem" | grep -v "^./.git"; then
          echo "::error::Sensitive files detected in PR"
          exit 1
        fi