name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history for GitVersion
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: '6.x'
          
      - name: Calculate version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4
        
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ steps.gitversion.outputs.majorMinorPatch }}
          name: v${{ steps.gitversion.outputs.majorMinorPatch }}
          tag: v${{ steps.gitversion.outputs.majorMinorPatch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}